#include <stdio.h>
#include <stdlib.h>
struct node
{                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
    int data;
    struct node *link;
} *head=NULL;
int length()
{
    int l=0;
    struct node*ptr=head;
    while(ptr!=NULL)
    {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
        l++;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
        ptr=ptr->link;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
    }     
    return l;            
}
void insert(int data,int pos)
{                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
    struct node *temp=malloc(sizeof(struct node));
    temp->data=data;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
    temp->link=NULL;
    int l=length();  
    struct node*ptr=head;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
    if(head==NULL)
    {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
        head=temp;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
    }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
    else if(pos==1)
    {
        temp->link=head;
        head=temp;
    }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
    else if(pos>l)
    {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
        ptr=head;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
        while(ptr->link!=NULL)
        {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
            ptr=ptr->link;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
        }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
        ptr->link=temp;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
    }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
    else
    {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
        pos--;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
        ptr=head;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
        while(pos!=1)
        {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
            ptr=ptr->link;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
            pos--;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
        }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
        temp->link=ptr->link;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
        ptr->link=temp;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
    }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
int delete(int pos)
{          
    int data;
    int l=length();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
    if(head==NULL)
    {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
        printf("Linked List Empty");
        return 0;
    }
    else if(pos==1)
    {
        struct node*temp;
        temp=head;
        head=head->link;
        free(temp);
        temp=NULL;
    }
    else if(head->link==NULL)
    {
        data=head->data;
        free(head);
        head=NULL;
    }
    else if(pos>l) 
    {
        struct node *temp,*ptr=head;
        ptr=head;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
        while(ptr->link->link!=NULL)
        {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
            ptr=ptr->link;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
        }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
        data=ptr->data;
        free(ptr->link);
        ptr->link=NULL;

    }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
    else
    {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
        struct node *temp,*ptr=head;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
        pos--;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
        while(pos!=1)
        {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
            ptr=ptr->link;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
            pos--;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
        }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
        temp=ptr->link; 
        data=temp->data;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
        ptr->link=temp->link;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
        free(temp);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
        temp=NULL;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
    } 
    return data;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
} 
void reverse()
{
    if(head==NULL)
    {
        printf("Linked List is Empty");
    }
    struct node *prev=NULL,*next=NULL;
    while(head!=NULL)
    {
        next=head->link;
        head->link=prev;
        prev=head;
        head=next;       
    }
    head=prev;
}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
void print()
{                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
    struct node*ptr=head;
    if(head==NULL)
    {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
        printf("Linked List Empty");
    }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
    else
    {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
        while(ptr!=NULL)
        {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
            printf("%d ",ptr->data);
            ptr=ptr->link;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
        }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
        printf("\n");
    }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
int main()
{                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
    while(1)
    {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
        int ch,data,pos;
        printf("\n---------------------------");
        printf("\n1.Insert");
        printf("\n2.Delete");
        printf("\n3.Reverse");
        printf("\n4.Print");
        printf("\n5.Exit");
        printf("\n----------------------------");
        printf("\nEnter your choice: ");
        scanf("%d",&ch);
        switch(ch)
        {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
            case 1:
            {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                printf("Enter data: ");
                scanf("%d",&data);
                printf("Enter position: ");
                scanf("%d",&pos);
                insert(data,pos);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                print();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                break;
            }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
            case 2:
            {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                printf("Enter position: " );
                scanf("%d",&pos);
                data=delete(pos);
                printf("Deleted element: %d\n",data);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                print();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                break;
            }
            case 3:
            {
                reverse();
                printf("\nReversed list");
                print();
                break;
            }     
            case 4:
            {
                printf("\nList: ");
                print();
                break;
            }
            case 5:
            {
                exit(1);
            }
            default:
            {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                printf("Invalid choice!!!");
                break;
            }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
        }
    }
    return 0;
}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                