#include <stdio.h>
#include <stdlib.h>
#include <string.h>
char stack[100];
int top=-1;
void push(char c)
{                                                                                                                                                                                                                                                                                                                                                                                                                                                                
        stack[++top]=c;                                                                                                                                                                                                                                                                                                                                                                                                                                          
}                                                                                                                                                                                                                                                                                                                                                                                                                                                                
char pop()
{                                                                                                                                                                                                                                                                                                                                                                                                                                                                
        char c;
        c=stack[top--];                                                                                                                                                                                                                                                                                                                                                                                                                                          
}                                                                                                                                                                                                                                                                                                                                                                                                                                                                
int isPalindrome(char*str)
{                                                                                                                                                                                                                                                                                                                                                                                                                                                                
        int i,l;
        char c;
        l=strlen(str);                                                                                                                                                                                                                                                                                                                                                                                                                                           
        for(i=0;i<l;i++)
        {                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                push(str[i]);                                                                                                                                                                                                                                                                                                                                                                                                                                    
        }                                                                                                                                                                                                                                                                                                                                                                                                                                                        
        for(i=0;i<l;i++)
        {                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                c=pop();                                                                                                                                                                                                                                                                                                                                                                                                                                         
                if(c!=str[i])
                {                                                                                                                                                                                                                                                                                                                                                                                                                                                
                        return 0;
                }                                                                                                                                                                                                                                                                                                                                                                                                                                                
        }                                                                                                                                                                                                                                                                                                                                                                                                                                                        
        return 1;
}                                                                                                                                                                                                                                                                                                                                                                                                                                                                
int main()
{                                                                                                                                                                                                                                                                                                                                                                                                                                                                
        char str[100];
        printf("Enter string: ");
        scanf("%s",str);
        if(isPalindrome(str))
        {                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                printf("Palindrome");
        }                                                                                                                                                                                                                                                                                                                                                                                                                                                        
        else
        {                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                printf("Not Palindrome");
        }                                                                                                                                                                                                                                                                                                                                                                                                                                                        
}  